author: 日志工具
author_url: http://it-boyer.github.io
github_url: https://github.com/it-boyer/LogSwift
root_url: https://github.com/it-boyer/LogSwift
module: LogSwiftForiOS
output: docs/iOS
theme: fullwidth
min_acl: internal
sdk: iphone
module_version: 1.0.0
xcodebuild_arguments: [-workspace,'../../hexo.xcworkspace', -scheme, 'LogSwiftForiOS',USE_SWIFT_RESPONSE_FILE=NO]
