author: 日志工具
author_url: http://huos3203.github.io
github_url: https://github.com/huos3203/LogSwift
root_url: https://github.com/huos3203/LogSwift
module: LogSwiftForiOS
output: docs/iOS
theme: fullwidth
min_acl: internal
sdk: iphone
module_version: 1.0.0
podspec: LogSwift.podspec
include: LogSwift/**/*.{swift,h}
xcodebuild_arguments: [-workspace, '../../hexo.xcworkspace', -scheme, 'LogSwiftForiOS']
