author: 日志工具OSX
author_url: http://huos3203.github.io
github_url: https://github.com/huos3203/LogSwift
root_url: https://github.com/huos3203/LogSwift
module: LogSwiftForOSX
output: docs/OSX
theme: fullwidth
min_acl: internal
module_version: 1.0.0
sdk: macosx
clean: true
xcodebuild_arguments: [-workspace, '../../hexo.xcworkspace', -scheme, 'LogSwiftForOSX',USE_SWIFT_RESPONSE_FILE=NO]
